hashicorp/go-oracle-terraform

- compute/instances.go
Unqualifies storageAttachments in an instance resource during a read
> Unqualify StorageAttachments in Instance

- compute/instances.go
This should fix the panic that Stephen encountered earlier today
> Adds error to unqualify nats

- client/client.go
- storage/authentication.go
- storage/container.go
- storage/container_test.go
- storage/storage_client.go
- storage/test_utils.go
This PR adds @grubernaut's review changes from #69.
> Fixing grubernauts comments

- compute/instances.go
This PR adds logs and increases the timeout for instance creation and deletion.
> Instance Log Enhancement

- client/client_test.go
- compute/compute_client.go
- compute/compute_client_test.go
- Ensuring we can successfully refresh the token
- Fixing the `make` build
> Auth Token Fix

- database/service_instance.go
- database/service_instance_test.go
This PR adds a method to turn `true` into `yes` and `false` into `no`. Open to name changes.
> Add bool to string method

- client/client.go
- storage/container.go
- storage/object.go
- storage/object_test.go
- storage/storage_client.go
- storage/storage_resource_client.go
- storage/test-fixtures/input.txt
Todo:
~~- [ ] Investigate Query Parameters~~ (Adding these as a future enhancement if needed for multi-part upload)
> Add storage objects

- database/service_instance.go
- database/service_instance_test.go
- java/service_instance.go
- java/service_instance_test.go
Merged a previous branch with master but didn't check for test passing. This PR fixes that.
```
make testacc TEST=./database TESTARGS="-run=TestAccServiceInstanceCloudStorage"
ORACLE_ACC=1 go test -v ./database -run=TestAccServiceInstanceCloudStorage -timeout 120m
=== RUN   TestAccServiceInstanceCloudStorage
--- PASS: TestAccServiceInstanceCloudStorage (2294.62s)
PASS
ok  	github.com/hashicorp/go-oracle-terraform/database	2294.638s
make testacc TEST=./java TESTARGS="-run=TestAccServiceInstance"
ORACLE_ACC=1 go test -v ./java -run=TestAccServiceInstance -timeout 120m
=== RUN   TestAccServiceInstanceLifeCycle
--- PASS: TestAccServiceInstanceLifeCycle (5907.73s)
PASS
ok …
```
> Database Parameter Fix

- compute/storage_volume_snapshots.go
An Oracle customer is hitting the timeout so this PR increases that timeout
> Increase timeout

- compute/orchestration.go
> Fixing errors

- compute/instances.go
Adding IsDefaultGateway attribute after it was removed in #91
> Readding IsDefaultGateway

- storage/container.go
- storage/container_test.go
- storage/object.go
- storage/object_test.go
- Adds support for including custom metadata headers on containers
- Adds support for including custom metadata headers on objects
- Adds support for Qutoas on containers
- Fixes creation of objects using "CopyFrom" option
> Object storage updates

- database/access_rules.go
This PR adds timeout support for deleting a database access rule
It also migrates Destination from `DB` to `DB_1` per the documentation.
> Adding timeout support for db accesss rules

- database/service_instance.go
> Add OCI support to sdk

- java/service_instance.go
This PR moves ProtectedRootContext to the correct struct
> Moving attribute to correct struct

- database/service_instance.go
This PR defaults the cloud storage user name and password of various fields when they are not specified.
> P default cs creds

- java/service_instance.go
Fixes typos for a couple of the API attribute names
> fix attribute names

- java/service_instance.go
updates the OTD loadbalancer policy constants
> updated loadbalancer policy constants

- database/service_instance.go
- java/service_instance.go
This PR should fix https://github.com/hashicorp/terraform-provider-oraclepaas/issues/34.
> Check for terminating state when creating instance

- database/access_rules.go
- database/access_rules_test.go
- helper/utils.go
This PR can obtain and update the default access rules for a database service instance
```
=== RUN   TestGetDefaultAccessRule_Basic
---PASS: TestGetDefaultAccessRule_Basic (47.03s)
=== RUN   TestUpdateDefaultAccessRule_Basic
--- PASS: TestUpdateDefaultAccessRule_Basic (114.11s)
```
> Get/Update default Access Rules

- database/access_rules.go
This PR just adds a nil check when updating a default access rule
> Adding nil check

- database/service_instance.go
This PR adds the standbys field for OCI
> Adding standbys field

- java/service_instance.go
Adding omitempty to cluster shape since it is an optional variable.
> Adding omitempty to cluster shape

- java/service_instance.go
- java/service_instance_test.go
This PR adds the ability to change the desired state of a java service instance
```
make testacc TEST=./java/ TESTARGS="-run=TestAccServiceInstanceLifeCycle_Stop"
ORACLE_ACC=1 go test -v ./java/ -run=TestAccServiceInstanceLifeCycle_Stop -timeout 120m
=== RUN   TestAccServiceInstanceLifeCycle_Stop
--- PASS: TestAccServiceInstanceLifeCycle_Stop (5044.85s)
PASS
ok  	github.com/hashicorp/go-oracle-terraform/java	5044.873s
```
> Java Service Instance LifeCycle

- mysql/access_rules_test.go
- mysql/service_instance.go
- mysql/service_instance_test.go
This PR uncomments the NotificationEmail parameter
> Fixing tests

- mysql/service_instance.go
- mysql/service_instance_test.go
There was an issue where the create would fail if no notification email was specified. This PR fixes that issue
> omitEmpty -> omitempty

- application/application_container.go
- application/application_container_test.go
- client/client.go
This PR uses the correct field name in the multipart form file
> P application additional fields

- compute/vpn_endpoint_v2.go
- compute/vpn_endpoint_v2_test.go
This PR adds VPN Endpoint V2 to the sdk. It's going to take a little more though to test this as we need an existing VPN Endpoint to get it working
> VPN Endpoint V2

- compute/compute_client.go
- compute/vpn_endpoint_v2.go
- Adds read only attributes for LocalGatewayIPAddress and LocalGatewayPrivateIPAddress
- Fixes updates
> VPNaaS v2 attribute updates

- java/service_instance.go
- java/service_instance_test.go
This PR adds the ability to scale out/in WebLogic Servers and the Oracle Traffic Director.
> New Feature: Scale Out/In WebLogic/OTD

- java/service_instance.go
- java/service_instance_test.go
This PR adds Profile to Java Service Instance to determine additional information around clusters
> Updating java service instance

- mysql/service_instance.go
Addressing https://github.com/terraform-providers/terraform-provider-oraclepaas/issues/69
> Move subnet attribute to correct location
