compute/ip_address_associations.go
compute/ip_address_associations_test.go

Adding ip address associations and test. 
```
make testacc TEST=./compute/ TESTARGS='-run=TestAccIPAddressAssociationsLifeCycle'
ORACLE_ACC=1 go test -v ./compute/ -run=TestAccIPAddressAssociationsLifeCycle -timeout 120m
=== RUN   TestAccIPAddressAssociationsLifeCycle
--- PASS: TestAccIPAddressAssociationsLifeCycle (122.56s)
PASS
ok  	github.com/hashicorp/go-oracle-terraform/compute	122.578s
```

Added ip address associations

---

compute/storage_volumes.go

When creating a Storage Volume, the user provides the Name of the Image List - but the ID is returned
```
image_list:       "/Compute-hashicorp/burzin@hashicorp.com/test-acc-stor-vol-bootable-image-list-3807614912818737137" => "test-acc-stor-vol-bootable-image-list-3807614912818737137" (forces new resource)
```
Tests pass:
```
$ envchain oracle make testacc TEST=./compute/ TESTARGS='-run=TestAccStorageVolume'
ORACLE_ACC=1 go test -v ./compute/ -run=TestAccStorageVolume -timeout 120m
=== RUN   TestAccStorageVolumeSnapshot_Lifecycle
--- PASS: TestAccStorageVolumeSnapshot_Lifecycle (16.74s)
=== RUN   TestAccStorageVolumeLifecycle
--- PASS: TestAccStorageVolumeLifecycle (15.05s)
=== RUN   TestAccStorageVolumeBootableLifecycle
--- …
```

Storage Volumes: unqualifying the Image List

---

compute/ssh_keys.go
compute/ssh_keys_integration_test.go

The Create API call for ssh keys doesn't accept any trailing comments in ssh keys. For example 
```ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC7BzZyp8CWN7tfIZiZwWx8H9RO2ClKu0ru...== your_email@example.com```, ```your_email@example.com``` will be lost in the call to create. This is problem in Terraform where Terraform will want to update the ssh key to add the trailing comment. To fix this, we just have immediately run update after we create the ssh key. 
This PR also updates the test to check the original key instead of the key we get back from the create call
```
make testacc TEST=./compute/ TESTARGS='-run=TestAccSSHKeyLifeCycle'
ORACLE_ACC=1 go test -v ./compute/ -run=TestAccSSHKeyLifeCycle -timeout 120m
=== RUN …
```

Fixes ssh key create error

---

compute/client.go
compute/client_test.go
compute/test_utils.go
opc/convert.go
scripts/errcheck.sh
vendor/gopkg.in/jarcoal/httpmock.v1/LICENSE
vendor/gopkg.in/jarcoal/httpmock.v1/README.md
vendor/gopkg.in/jarcoal/httpmock.v1/doc.go
vendor/gopkg.in/jarcoal/httpmock.v1/env.go
vendor/gopkg.in/jarcoal/httpmock.v1/response.go
vendor/gopkg.in/jarcoal/httpmock.v1/transport.go
vendor/vendor.json

Allows `max_retries` to be set during the provider configuration.
```
$ make test TEST=./compute TESTARGS="-v -run=TestClient_retryHTTP"
==> Checking for unchecked errors...
go test -i ./compute || exit 1
echo ./compute | \
xargs -t -n4 go test -v -run=TestClient_retryHTTP -timeout=30s -parallel=4
go test -v -run=TestClient_retryHTTP -timeout=30s -parallel=4 ./compute
=== RUN   TestClient_retryHTTP
--- PASS: TestClient_retryHTTP (0.00s)
PASS
ok      github.com/hashicorp/go-oracle-terraform/compute        0.010s
```

opc: Add max_retries capabilities

---

client/client.go
storage/authentication.go
storage/authentication_test.go
storage/container.go
storage/container_test.go
storage/storage_client.go
storage/storage_resource_client.go
storage/test_utils.go

This PR adds the first PaaS resource (Storage containers) to the oracle sdk. 
```
TF_ACC=1 make test TEST=./storage TESTARGS="-v -run=TestAccContainerLifeCycle"
==> Checking for unchecked errors...
go test -i ./storage || exit 1
echo ./storage | \
xargs -t -n4 go test -v -run=TestAccContainerLifeCycle -timeout=60m -parallel=4
go test -v -run=TestAccContainerLifeCycle -timeout=60m -parallel=4 ./storage
=== RUN   TestAccContainerLifeCycle
--- PASS: TestAccContainerLifeCycle (1.89s)
PASS
ok  	github.com/hashicorp/go-oracle-terraform/storage	1.914s
```

Adding storage containers

---

client/client.go
compute/instances.go
compute/instances_test.go
storage/container_test.go

This PR adds logic to tear down and recreate an instance that is in an errored state 
```
make test TEST=./compute TESTARGS="-v -run=TestInstanceClient_CreateInstanceError"
==> Checking for unchecked errors...
go test -i ./compute || exit 1
echo ./compute | \
xargs -t -n4 go test -v -run=TestInstanceClient_CreateInstanceError -timeout=60m -parallel=4
go test -v -run=TestInstanceClient_CreateInstanceError -timeout=60m -parallel=4 ./compute
=== RUN   TestInstanceClient_CreateInstanceError
--- PASS: TestInstanceClient_CreateInstanceError (2.01s)
PASS
ok  	github.com/hashicorp/go-oracle-terraform/compute	2.035s
```

P instance retry

---

storage/storage_client.go
storage/test_utils.go

This PR switches the sdk from building the url to the user passing their storage url through the `Config` struct or through the `OPC_STORAGE_ENDPOINT` flag
```
make test TEST=./storage TESTARGS="-v -run=TestAcc"
==> Checking for unchecked errors...
go test -i ./storage || exit 1
echo ./storage | \
xargs -t -n4 go test -v -run=TestAcc -timeout=60m -parallel=4
go test -v -run=TestAcc -timeout=60m -parallel=4 ./storage
=== RUN   TestAccObtainAuthenticationToken
--- PASS: TestAccObtainAuthenticationToken (0.60s)
=== RUN   TestAccContainerLifeCycle
--- PASS: TestAccContainerLifeCycle (1.88s)
PASS
ok  	github.com/hashicorp/go-oracle-terraform/storage	2.512s
```

Storage URL

---

client/client.go
compute/instances.go
compute/instances_integration_test.go
compute/snapshots.go
compute/ssh_keys_test.go
compute/storage_volume_attachments.go
compute/storage_volume_attachments_test.go
compute/storage_volume_snapshots.go
compute/storage_volumes.go
compute/storage_volumes_test.go

Add timeouts to input structs to allow setting timeouts inside the TF provider, which is the first step to adding timeouts to the OPC provider.
Next step is to setup timeouts in the provider.
```
$ make testacc TEST=./compute
ORACLE_ACC=1 go test -v ./compute  -timeout 120m
=== RUN   TestAccACLLifeCycle
--- PASS: TestAccACLLifeCycle (5.56s)
=== RUN   TestAccACLsClient_CreateRule
--- PASS: TestAccACLsClient_CreateRule (0.00s)
=== RUN   TestAccObtainAuthenticationCookie
--- PASS: TestAccObtainAuthenticationCookie (0.00s)
=== RUN   TestAccAuthenticationCookieSentInRequestsFromAuthenticatedClient
--- PASS: TestAccAuthenticationCookieSentInRequestsFromAuthenticatedClient (0.00s)
=== RUN   TestClient_qualifyList
--- PASS: …
```

Add timeouts, update WaitFor()

---

database/authentication.go
database/database_client.go
database/database_resource_client.go
database/service_instance.go
database/service_instance_test.go
database/test_utils.go

This PR adds the [Oracle Database Service Instance](http://docs.oracle.com/en/cloud/paas/database-dbaas-cloud/csdbr/api-Service%20Instances.html). Our testing account only allows us to test the `PAAS` level and not the `BASIC` level. 
```
make testacc TEST=./database TESTARGS="-run=TestAccServiceInstanceLifeCycle"
ORACLE_ACC=1 go test -v ./database -run=TestAccServiceInstanceLifeCycle -timeout 120m
=== RUN   TestAccServiceInstanceLifeCycle
--- PASS: TestAccServiceInstanceLifeCycle (1724.32s)
PASS
ok  	github.com/hashicorp/go-oracle-terraform/database	1724.347s
```

Add database service instance

---

database/service_instance.go

This updates the sleep check for deleting a resource since the time between a resource being usable after an instance has been configured varies greatly. This also adds more attributes to the ServiceInstance struct.

Updating attributes

---

storage/object.go
storage/object_test.go

Adds an `id` helper attribute to make the provider a little easier to
navigate, especially during an import.
```
$ make testacc TEST=./storage TESTARGS="-run=TestAccObjectLifeCycle_contentSourceID"
ORACLE_ACC=1 go test -v ./storage -run=TestAccObjectLifeCycle_contentSourceID -timeout 120m
=== RUN   TestAccObjectLifeCycle_contentSourceID
--- PASS: TestAccObjectLifeCycle_contentSourceID (1.59s)
PASS
ok      github.com/hashicorp/go-oracle-terraform/storage        1.590s
```

storage_object: Add `id` helper attribute

---

storage/container.go
storage/container_test.go

This PR fixes allowed origins and adds exposed headers. 
```
make testacc TEST=./storage TESTARGS="-run=TestAccContainerLifeCycle"
ORACLE_ACC=1 go test -v ./storage -run=TestAccContainerLifeCycle -timeout 120m
=== RUN   TestAccContainerLifeCycle
--- PASS: TestAccContainerLifeCycle (2.13s)
PASS
ok  	github.com/hashicorp/go-oracle-terraform/storage	2.148s
```

Added exposed headers and fixed allowed origins

---

compute/storage_volumes.go

Previously we were only capturing errors returned from the API, not any
errors on Storage Volume creation, thus causing the storage volume to sit
in a wait-ready loop until we hit a timeout, even if the storage volume
had failed to create a long time ago.
This checks if the returned storage volume's status contains `"error"`,
and returns the status detailed text, if so.

storage_volumes: Actually capture errors during a storage volume create

---

client/client.go
compute/compute_client.go
database/access_rules.go
database/access_rules_test.go
database/database_client.go
database/database_resource_client.go
database/service_instance.go
database/ssh_keys.go
database/ssh_keys_test.go
database/utility_resource_client.go
database/utility_test.go

Bugfix: 
- Fixes Debug Log issue where HTTP Request bodies were no longer being printed in their actual JSON form, but the Golang Struct that built the JSON request. This was fixed by splitting out the JSON marshaling from the request building, and deprecates the original `BuidlRequest` method.
Note: Adds two helper functions for iterating and working on PaaS DB resources.
`TestAccDataBaseClient_CreateStandalone` and `TestAccDataBaseClient_DestroyStandalone`.
`TestAccDataBaseClient_CreateStandalone`, will only run if the
`OPC_TEST_DB` environment variable is populated. This ensure's we don't
leak service instances during our nightly acceptance tests, as this env
var will not be set. The test function, when ran like so:
```
$ OPC_TEST_DB=1 make testacc TEST=./database …
```

database: Add utility resources

---

java/service_instance.go
java/service_instance_test.go

This PR adds extra tests to go-oracle-terraform and fixes code to make them work.
```
make testacc TEST=./java TESTARGS="-run=TestAccServiceInstance"
ORACLE_ACC=1 go test -v ./java -run=TestAccServiceInstance -timeout 120m
=== RUN   TestAccServiceInstanceLifeCycle
--- PASS: TestAccServiceInstanceLifeCycle (4619.20s)
=== RUN   TestAccServiceInstanceLifeCycle_typeOTD
--- PASS: TestAccServiceInstanceLifeCycle_typeOTD (4585.08s)
=== RUN   TestAccServiceInstanceLifeCycle_typeDatagrid
--- PASS: TestAccServiceInstanceLifeCycle_typeDatagrid (3027.95s)
PASS
```

P java service instance

---

compute/instances.go

Add the `is_default_gateway` attribute used to designate the default gateway interface for IP Network interfaces

Add attribute for is_default_gateway

---

client/client.go
client/client_test.go
client/version.go
java/java_client.go
opc/config.go

Adding UserAgent to the client and removing a deprecated method
```
make testacc TEST=./client TESTARGS="-run=TestClient_userAgent"
ORACLE_ACC=1 go test -v ./client -run=TestClient_userAgent -timeout 120m
=== RUN   TestClient_userAgent
--- PASS: TestClient_userAgent (0.00s)
PASS
ok  	github.com/hashicorp/go-oracle-terraform/client	0.011s```

Adding UserAgent to client

---

compute/orchestration.go
compute/orchestration_test.go

Adding a test to make sure suspending an orchestration works properly
```
OPC_LOG=1 make testacc TEST=./compute TESTARGS="-run=TestAccOrchestrationLifeCycle_suspend"
ORACLE_ACC=1 go test -v ./compute -run=TestAccOrchestrationLifeCycle_suspend -timeout 120m
=== RUN   TestAccOrchestrationLifeCycle_suspend
--- PASS: TestAccOrchestrationLifeCycle_suspend (148.32s)
PASS
ok  	github.com/hashicorp/go-oracle-terraform/compute	148.344s
```

Add suspend test

---

compute/storage_volume_attachments.go

Quick bugfix where storage volume name wasn't being qualified.

Fixing storage volume name issue

---

compute/orchestration.go
compute/orchestration_test.go

This PR fixes Relationships between objects for orchestrated instances.
```
make testacc TEST=./compute TESTARGS="-run=TestAccOrchestrationLifeCycle_relationship"
ORACLE_ACC=1 go test -v ./compute -run=TestAccOrchestrationLifeCycle_relationship -timeout 120m
=== RUN   TestAccOrchestrationLifeCycle_relationship
--- PASS: TestAccOrchestrationLifeCycle_relationship (775.40s)
PASS
ok  	github.com/hashicorp/go-oracle-terraform/compute	775.421s
```

Adding relationships test to orchestrated instances

---

database/access_rules.go
java/access_rules.go
java/access_rules_test.go
java/java_client.go
java/service_instance.go
java/utility_resource_client.go

This PR adds Java Access Rules to the go-sdk
```
make testacc TEST=./java TESTARGS="-run=TestAccAccessRulesLifeCycle"
ORACLE_ACC=1 go test -v ./java -run=TestAccAccessRulesLifeCycle -timeout 120m
=== RUN   TestAccAccessRulesLifeCycle
--- PASS: TestAccAccessRulesLifeCycle 
PASS
ok  	github.com/hashicorp/go-oracle-terraform/java	
```

Adding java access rules

---

database/database_client.go
java/java_client.go

Small fix for an odd bug - I noticed the database JSON request payloads weren't appearing in the debug logs, adding an extra character after \n in the Sprintf fixes it!?
Also made the Java client debug output consistent.

Fix debug log

---

README.md
compute/image_list_entries_test.go
compute/instances_integration_test.go
compute/instances_test.go
compute/ip_associations_test.go
compute/orchestration_test.go
compute/security_associations_test.go
compute/snapshots_test.go
compute/storage_volume_attachments_integration_test.go
compute/storage_volumes_integration_test.go
compute/virtual_nic_test.go

- Updated tests to consistently use the `/oracle/public/OL_7.2_UEKR4_x86_64` image list. This image is faster to launch than some of the older images user. Seeing about 25% reduction in time to execute all tests.
- Removed unnecessary creation of temporary image list for some test cases. Tests now use the main image list directly.

Consistent use of Image List in Acceptance tests.

---

database/service_instance.go

`AvailabilityDomain` json attribute name mapping was incorrect, so SDK was always returning `AvailabilityDomain` as blank.

fix Availablility Domain json attribute name

---

database/service_instance.go

The boolean values for rac, ibkup, hdg, etc are best omitted when false rather than  setting to "no" as some combinations of settings expect the value to be omitted when the value is not relevant.  The default when not set is "no"
One specific issue is with snapshots which fails validation if `ibkup: "no"` is set, as it expects ibkup to be omitted.

omit boolean attributes when false

---

database/service_instance.go
database/service_instance_test.go

Fixes the WaitForServiceInstanceRunning() to wait for "Running" instead of waiting for "Configured" + 10 minutes.
Resolves the issue where provisioning fails when state goes from "In Progress -> Configured -> Running" between polls so Configured status is never seen.

Fix to monitor for Ready state

---

database/service_instance.go
java/service_instance.go

Adds the supported OCI Shapes as per the Java Cloud Service API documentation:
> On Oracle Cloud Infrastructure, only VM.Standard and BM.Standard shapes are supported.

add supported oci shapes

---

database/access_rules.go
database/access_rules_test.go

This PR optimizes the DefaultAccessRules to only call the GetApi one time instead of for every default access rule. Tests are much faster
```
=== RUN   TestGetDefaultAccessRule_Basic
--- PASS: TestGetDefaultAccessRule_Basic (6.54s)
=== RUN   TestUpdateDefaultAccessRule_Basic
--- PASS: TestUpdateDefaultAccessRule_Basic (38.42s)
```

Optimizing default access rules

---

java/service_instance.go

This PR trims ssh keys with trailing content that caused the JCS API to error. 
Fixes https://github.com/hashicorp/terraform-provider-oraclepaas/issues/18

Java ssh key trim

---

client/client.go

Java Service Instance Deletion was returning an error message of `No such service exits` instead of a 404. This PR adds an extra check in the WasNotFound method.

Additional not found check

---

database/service_instance.go
database/service_instance_test.go

This PR adds the ability to scale up and down a service instance 
```
make testacc TEST=./database TESTARGS="-run=TestAccServiceInstanceUpdate"
ORACLE_ACC=1 go test -v ./database -run=TestAccServiceInstanceUpdate -timeout 120m
=== RUN   TestAccServiceInstanceUpdate
--- PASS: TestAccServiceInstanceUpdate (3458.23s)
PASS
ok  	github.com/hashicorp/go-oracle-terraform/database	3458.248s
```

P scale db

---

database/database_resource_client.go
database/service_instance.go
database/service_instance_test.go

This PR adds the ability to set the desired state of a database service instance 
```
make testacc TEST=./database  TESTARGS="-run=TestAccServiceInstanceDesiredState"
ORACLE_ACC=1 go test -v ./database -run=TestAccServiceInstanceDesiredState -timeout 120m
=== RUN   TestAccServiceInstanceDesiredState
--- PASS: TestAccServiceInstanceDesiredState (3841.91s)
PASS
ok  	github.com/hashicorp/go-oracle-terraform/database	3841.928s
```

P db desired state

---

database/access_rules.go
java/access_rules.go
java/service_instance.go

The Middleware Version tends to change more frequently than users would like. We're omitting it here so users can use the latest version when it arrives rather than waiting for an sdk release and then a provider release.
Also this PR bumps out the Timeout to the correct time in minutes rather than seconds

Removing constants from Service Version

---

java/service_instance.go

Adds support for setting `assignPublicIP` when creating JCS instances.

Add assignPublicIP attribute for Java Cloud Service

---

java/access_rules.go
java/service_instance.go

```
make testacc TEST=./java/ TESTARGS="-run=TestAccAccessRulesLifeCycle"
ORACLE_ACC=1 go test -v ./java/ -run=TestAccAccessRulesLifeCycle -timeout 120m
=== RUN   TestAccAccessRulesLifeCycle
--- PASS: TestAccAccessRulesLifeCycle (4793.83s)
PASS
ok  	github.com/hashicorp/go-oracle-terraform/java	4793.853s
```

Adding additional checks for access rules and service instance

---

mysql/mysql_client.go

Adds HTTP Request body logging the the MySQL client to aid debugging provisioning issues - same is JCS and DBCS clients.

Add Mysql API request logging

---

application/application_client.go
application/application_container.go
application/application_container_test.go
application/application_resource_client.go
application/utils_test.go
client/client.go

This PR adds the ability to pass in the manifest and deployment attributes into the sdk rather than those respective files
```
=== RUN   TestAccApplicationContainerLifeCycle_Basic
--- PASS: TestAccApplicationContainerLifeCycle_Basic (175.06s)
=== RUN   TestAccApplicationContainerLifeCycle_ManifestFile
--- PASS: TestAccApplicationContainerLifeCycle_ManifestFile (188.34s)
=== RUN   TestAccApplicationContainerLifeCycle_TwoManifest
--- PASS: TestAccApplicationContainerLifeCycle_TwoManifest (0.00s)
=== RUN   TestAccApplicationContainerLifeCycle_ManifestAttr
--- PASS: TestAccApplicationContainerLifeCycle_ManifestAttr (203.62s)
=== RUN   TestAccApplicationContainerLifeCycle_Deployment
--- PASS: TestAccApplicationContainerLifeCycle_Deployment (119.09s)
=== RUN …
```

P application container

---

java/java_resource_client.go
java/jobs.go
java/service_instance.go

This PR adds the ability to check the status of a job acting on a java service instance. So far this is only used for updating a service instance.
```
=== RUN   TestAccServiceInstanceLifeCycle_ScaleUp
--- PASS: TestAccServiceInstanceLifeCycle_ScaleUp (582.42s)
=== RUN   TestAccServiceInstanceLifeCycle_Stop
--- PASS: TestAccServiceInstanceLifeCycle_Stop (308.04s)
```

Adding jobs to java service instance

---

compute/instances.go

This SDK fix addresses the terraform-provider-opc issue https://github.com/terraform-providers/terraform-provider-opc/issues/138
Fixes the unqualification of the fully qualified SecList name.

fix unqualification of SecList name

---

storage/container.go

Resolves issues with environments without Quotas where headers are not set.  Meta headers should be considered optional, removed fail on error.

resolve issue parsing optional storage headers

---

java/service_instance.go

This update removes the `omitempty` on the ProvisionOTD so the `provisionOTD` is always explicitly set in the create request to resolve issue where the provisionOTM default changes depending on the number of managed servers defined.

force ProvisionOTD to be set

---

README.md
database/ip_reservation.go
database/ip_reservation_resource_client.go
database/ip_reservation_test.go
database/jobs.go
database/service_instance.go
java/ip_reservation.go
java/ip_reservation_resource_client.go
java/ip_reservation_test.go
java/jobs.go
java/service_instance.go
mysql/ip_reservation.go
mysql/ip_reservation_resource_client.go
mysql/ip_reservation_test.go
mysql/jobs.go

Adds SDK support for the PaaS Services IP Reservation APIs:
- [Database Cloud Service IP Reservations](https://docs.oracle.com/en/cloud/paas/database-dbaas-cloud/csdbr/api-ip-reservations.html)
- [MySQL Cloud Service IP Reservations](https://docs.oracle.com/cloud/latest/mysql-cloud/CSMCS/api-ip-reservations.html)
- [Java Cloud Service IP Reservations](https://docs.oracle.com/en/cloud/paas/java-cloud/jsrmr/api-ip-reservations.html)

Add IP Reservations for PaaS Services

---

database/service_instance.go
java/service_instance.go

SDK update to address  https://github.com/terraform-providers/terraform-provider-oraclepaas/issues/45
Updates the database service and java service IP Reservations attributes type from []string to string as the API takes a single string with a comma separated list of IP Reservations names, not a list of strings.

Fix dbcs/jcs IP Reservations attribute type

---

client/client.go
database/access_rules_test.go

This PR address an issue identified https://github.com/terraform-providers/terraform-provider-opc/issues/148 where the retries always fail for requests the Body (POST/PUT) as the body of the request in unreadable after
This update also adds an exponential backoff to the retries, with a 60 second maximum delay.

Fix retry logic

---

storage/storage_client.go

This small fix removes the leading `/` in cloud account username that was causing a issue with authentication for IDCS Cloud Accounts but worked with Traditional accounts.  Without the leading '/' authentication is successful for both Traditional and IDCS Cloud accounts.
Tests run against a Traditional Account:
```
$ make testacc TEST=./storage
ORACLE_ACC=1 go test -v ./storage  -timeout 120m
=== RUN   TestAccObtainAuthenticationToken
--- PASS: TestAccObtainAuthenticationToken (1.26s)
=== RUN   TestAccContainerLifeCycle
--- PASS: TestAccContainerLifeCycle (4.64s)
=== RUN   Test_isCustomHeader
--- PASS: Test_isCustomHeader (0.23s)
=== RUN   Test_updateOrRemoveHeadersStringValue
--- PASS: Test_updateOrRemoveHeadersStringValue …
```

fix username format to work with IDCS Cloud Accounts

---

application/application_container.go

Adds additional attributes added to the API in release `2018.08.21` to support deploying ACCS applications to OCI regions.
https://docs.oracle.com/en/cloud/paas/app-container-cloud/apcsr/op-paas-service-apaas-api-v1.1-apps-identitydomainid-post.html

Add extra attributes for ACCS on OCI

---

compute/instances.go

This is needed for a packer feature. Tests didn't seem necessary, but let me know if you want me to add them

Add ImageListEntry to CreateInstanceInput

---

java/service_instance.go
java/service_instance_test.go
lbaas/policy_test.go

Adds additional Java Cloud Service attributes for provisioning an Oracle Managed Load Balancer as part of the service instance configuration
- `ConfigureLoadBalancer`
- `LoadBalancerType`
- `LoadBalancer.Subnets`
Required for https://github.com/terraform-providers/terraform-provider-oraclepaas/issues/52

add attributes for oracle managed load balancer

---

compute/compute_client.go
compute/instances_integration_test.go

This PR allows users to specify resource names from across users by not un-qualifying the resource name if a different username or identity domain is specified.

Feature: Specify cross user resource

---

compute/instances.go

This fix resolves a crash with the terraform-provider-opc when the instance details return `nat: "null"` rather than `null` or a list which has been observed in some cases after a host crash. The crash with terraform provider prevents restarting the failed instance.  
```
"networking": {
"eth0": {
"model": "e1000",
"seclists": [
"/Compute-a123456/user@example.com/oraclemigration"
],
"dns": [
"oraclemigration.compute-a123456.oraclecloud.internal."
],
"vethernet": "/oracle/public/default",
"nat": "null"
}
},
```

fix crash when instance nat attribute is "null" string

---

compute/instances.go

Partially resolves opc provider issue https://github.com/terraform-providers/terraform-provider-opc/issues/174
This fix allows for instance names with path separators

allow instance names with multiple path separators
